{
  "openapi": "3.0.1",
  "info": {
    "description": "Спецификация описывает набор endpoints для работы с комментариями к событиям.\n\nEndpoins разделены на 3 части: \n\n1. Пользователь может оставить комментарий, редактировать его и удалить.\n\n2. Администратор (модератор) может reject (скрыть) комментарий, либо approve (вернуть) скрытый комментарий. По умолчанию все комментарии открыты. Также админ может искать в комментах по тексту, чтобы найти экстремизм. Может запрашивать все комментарии конкретного пользователя для отчета в ФСБ. А может полностью удалять комменты скрывая следы преступления.\n\n3. Неограниченный круг лиц может прочитать конкретный коммент к событию. Может прочитать все комменты к событию. Также можно запросить коммент по ID без привязки к событию.",
    "title": "Описание API фичи \"Комментарии\"",
    "version": "1.0"
  },
  "servers": [
    {
      "description": "Generated server url",
      "url": "http://localhost:8080"
    }
  ],
  "tags": [
    {
      "description": "API комментатора",
      "name": "Private: Комментарии"
    },
    {
      "description": "API администратора",
      "name": "Admin: Комментарии"
    },
    {
      "description": "Публичный API",
      "name": "Public: Комментарии"
    }
  ],
  "paths": {
    "/users/{userId}/events/{eventId}/comments": {
      "post": {
        "description": "Пользователь userId добавляет новый комментарий к событию eventId",
        "operationId": "addComment",
        "parameters": [
          {
            "description": "id комментатора",
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "description": "id комментируемого события",
            "in": "path",
            "name": "eventId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CommentCreateDto"
              }
            }
          },
          "description": "данные добавляемого комментария",
          "required": true
        },
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommentDto"
                }
              }
            },
            "description": "Комментарий добавлен"
          },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Field: text. Error: must not be blank. Value: null",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Запрос составлен некорректно"
          },
          "404": {
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Event with id=27 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Событие не найдено"
          },
          "409": {
            "content": {
              "application/json": {
                "example": {
                  "status": "CONFLICT",
                  "reason": "Forbidden action",
                  "message": "You can comment PUBLISHED events only!",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Нарушение ограничений бизнес-логики"
          }
        },
        "summary": "Добавление нового комментария",
        "tags": [
          "Private: Комментарии"
        ]
      }
    },
    "/users/{userId}/comments/{comId}": {
      "delete": {
        "description": "Пользователь userId удаляет свой комментарий comId",
        "operationId": "deleteComment",
        "parameters": [
          {
            "description": "id комментатора",
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "description": "id комментария",
            "in": "path",
            "name": "comId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Комментарий удален"
          },
          "404": {
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Comment with id=27 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Комментарий не найден"
          },
          "409": {
            "content": {
              "application/json": {
                "example": {
                  "status": "CONFLICT",
                  "reason": "Unauthorized access by user",
                  "message": "You can delete your own comment only!",
                  "timestamp": "2023-01-21 16:56:19"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Нарушение ограничений"
          }
        },
        "summary": "Удаление комментария",
        "tags": [
          "Private: Комментарии"
        ]
      },
      "patch": {
        "description": "Пользователь userId редактирует свой комментарий comId",
        "operationId": "updateComment",
        "parameters": [
          {
            "description": "id комментатора",
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "description": "id комментария",
            "in": "path",
            "name": "comId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CommentCreateDto"
              }
            }
          },
          "description": "Данные комментария для изменения",
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommentDto"
                }
              }
            },
            "description": "Данные комментария изменены"
          },
          "404": {
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Comment with id=27 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Комментарий не найден"
          },
          "409": {
            "content": {
              "application/json": {
                "example": {
                  "status": "CONFLICT",
                  "reason": "Unauthorized access by user",
                  "message": "You can edit your own comments only!",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Нарушение ограничений"
          }
        },
        "summary": "Редактирование комментария",
        "tags": [
          "Private: Комментарии"
        ]
      }
    },
    "/admin/comments/search": {
      "get": {
        "description": "Возвращает все комментарии с заданным текстом. Постранично.\nЕсли не найдено ничего, возвращает пустой список",
        "operationId": "searchComments",
        "parameters": [
          {
            "description": "текст для поиска",
            "in": "query",
            "name": "text",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "количество комментариев, которые нужно пропустить",
            "in": "query",
            "name": "from",
            "required": false,
            "schema": {
              "minimum": 0,
              "type": "integer",
              "format": "int32",
              "default": 0
            }
          },
          {
            "description": "количество комментариев в наборе",
            "in": "query",
            "name": "size",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CommentDto"
                  }
                }
              }
            },
            "description": "Комментарии найдены"
          },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type int; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Запрос составлен некорректно"
          }
        },
        "summary": "Поиск комментариев по тексту",
        "tags": [
          "Admin: Комментарии"
        ]
      }
    },
    "/admin/users/{userId}/comments": {
      "get": {
        "description": "Возвращает все комментарии заданного пользователя. Постранично.\nЕсли не найдено ничего, возвращает пустой список",
        "operationId": "getUserComments",
        "parameters": [
          {
            "description": "id комментатора",
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "description": "количество комментариев, которые нужно пропустить",
            "in": "query",
            "name": "from",
            "required": false,
            "schema": {
              "minimum": 0,
              "type": "integer",
              "format": "int32",
              "default": 0
            }
          },
          {
            "description": "количество комментариев в наборе",
            "in": "query",
            "name": "size",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CommentDto"
                  }
                }
              }
            },
            "description": "Комментарии найдены"
          },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type int; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Запрос составлен некорректно"
          }
        },
        "summary": "Поиск комментариев заданного пользователя",
        "tags": [
          "Admin: Комментарии"
        ]
      }
    },
    "/admin/comments/{comId}": {
      "delete": {
        "description": "Администратор удаляет комментарий comId",
        "operationId": "deleteCommentByAdmin",
        "parameters": [
          {
            "description": "id комментария",
            "in": "path",
            "name": "comId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Комментарий удален"
          },
          "404": {
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Comment with id=27 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Комментарий не найден"
          }
        },
        "summary": "Удаление комментария администратором",
        "tags": [
          "Admin: Комментарии"
        ]
      }
    },
    "/admin/comments/{comId}/approve": {
      "patch": {
        "description": "Администратор делает комментарий видимым",
        "operationId": "approveComment",
        "parameters": [
          {
            "description": "id комментария",
            "in": "path",
            "name": "comId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommentDto"
                }
              }
            },
            "description": "Комментарий одобрен"
          },
          "404": {
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Comment with id=2727 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Комментарий не найден"
          }
        },
        "summary": "Одобрение комментария",
        "tags": [
          "Admin: Комментарии"
        ]
      }
    },
    "/admin/comments/{comId}/reject": {
      "patch": {
        "description": "Администратор делает комментарий невидимым",
        "operationId": "rejectComment",
        "parameters": [
          {
            "description": "id комментария",
            "in": "path",
            "name": "comId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommentDto"
                }
              }
            },
            "description": "Комментарий отклонен"
          },
          "404": {
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Comment with id=2727 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Комментарий не найден"
          }
        },
        "summary": "Отклонение комментария",
        "tags": [
          "Admin: Комментарии"
        ]
      }
    },
    "/comments/{comId}": {
      "get": {
        "description": "Возвращает конкретный комментарий по ID",
        "operationId": "getComment",
        "parameters": [
          {
            "description": "id комментария",
            "in": "path",
            "name": "comId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommentDto"
                }
              }
            },
            "description": "Комментарий найден"
          },
          "404": {
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Comment with id=2727 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Комментарий не найден"
          }
        },
        "summary": "Комментарий по ID",
        "tags": [
          "Public: Комментарии"
        ]
      }
    },
    "/events/{eventId}/comments/{commentId}": {
      "get": {
        "description": "Возвращает комментарий commentId к событию eventId",
        "operationId": "getCommentRelatedToEvent",
        "parameters": [
          {
            "description": "id события",
            "in": "path",
            "name": "eventId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "description": "id комментария",
            "in": "path",
            "name": "commentId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CommentDto"
                }
              }
            },
            "description": "Комментарий найден"
          },
          "404": {
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Comment with id=2727 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Комментарий не найден"
          }
        },
        "summary": "Комментарий к конкретному событию",
        "tags": [
          "Public: Комментарии"
        ]
      }
    },
    "/events/{eventId}/comments": {
      "get": {
        "description": "Возвращает все комментарии к заданному событию. Постранично.\nЕсли не найдено ничего, возвращает пустой список",
        "operationId": "getEventComments",
        "parameters": [
          {
            "description": "id события",
            "in": "path",
            "name": "eventId",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "description": "количество комментариев, которые нужно пропустить",
            "in": "query",
            "name": "from",
            "required": false,
            "schema": {
              "minimum": 0,
              "type": "integer",
              "format": "int32",
              "default": 0
            }
          },
          {
            "description": "количество комментариев в наборе",
            "in": "query",
            "name": "size",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CommentShortDto"
                  }
                }
              }
            },
            "description": "Комментарии найдены"
          },
          "404": {
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Event with id=2727 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            },
            "description": "Событие не найдено"
          }
        },
        "summary": "Поиск комментариев к конкретному событию",
        "tags": [
          "Public: Комментарии"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "ApiError": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "description": "Список стектрейсов или описания ошибок",
            "example": [],
            "items": {
              "type": "string",
              "description": "Список стектрейсов или описания ошибок",
              "example": "[]"
            }
          },
          "message": {
            "type": "string",
            "description": "Сообщение об ошибке",
            "example": "Only pending or canceled events can be changed"
          },
          "reason": {
            "type": "string",
            "description": "Общее описание причины ошибки",
            "example": "For the requested operation the conditions are not met."
          },
          "status": {
            "type": "string",
            "description": "Код статуса HTTP-ответа",
            "example": "FORBIDDEN",
            "enum": [
              "100 CONTINUE",
              "101 SWITCHING_PROTOCOLS",
              "102 PROCESSING",
              "103 CHECKPOINT",
              "200 OK",
              "201 CREATED",
              "202 ACCEPTED",
              "203 NON_AUTHORITATIVE_INFORMATION",
              "204 NO_CONTENT",
              "205 RESET_CONTENT",
              "206 PARTIAL_CONTENT",
              "207 MULTI_STATUS",
              "208 ALREADY_REPORTED",
              "226 IM_USED",
              "300 MULTIPLE_CHOICES",
              "301 MOVED_PERMANENTLY",
              "302 FOUND",
              "302 MOVED_TEMPORARILY",
              "303 SEE_OTHER",
              "304 NOT_MODIFIED",
              "305 USE_PROXY",
              "307 TEMPORARY_REDIRECT",
              "308 PERMANENT_REDIRECT",
              "400 BAD_REQUEST",
              "401 UNAUTHORIZED",
              "402 PAYMENT_REQUIRED",
              "403 FORBIDDEN",
              "404 NOT_FOUND",
              "405 METHOD_NOT_ALLOWED",
              "406 NOT_ACCEPTABLE",
              "407 PROXY_AUTHENTICATION_REQUIRED",
              "408 REQUEST_TIMEOUT",
              "409 CONFLICT",
              "410 GONE",
              "411 LENGTH_REQUIRED",
              "412 PRECONDITION_FAILED",
              "413 PAYLOAD_TOO_LARGE",
              "413 REQUEST_ENTITY_TOO_LARGE",
              "414 URI_TOO_LONG",
              "414 REQUEST_URI_TOO_LONG",
              "415 UNSUPPORTED_MEDIA_TYPE",
              "416 REQUESTED_RANGE_NOT_SATISFIABLE",
              "417 EXPECTATION_FAILED",
              "418 I_AM_A_TEAPOT",
              "419 INSUFFICIENT_SPACE_ON_RESOURCE",
              "420 METHOD_FAILURE",
              "421 DESTINATION_LOCKED",
              "422 UNPROCESSABLE_ENTITY",
              "423 LOCKED",
              "424 FAILED_DEPENDENCY",
              "425 TOO_EARLY",
              "426 UPGRADE_REQUIRED",
              "428 PRECONDITION_REQUIRED",
              "429 TOO_MANY_REQUESTS",
              "431 REQUEST_HEADER_FIELDS_TOO_LARGE",
              "451 UNAVAILABLE_FOR_LEGAL_REASONS",
              "500 INTERNAL_SERVER_ERROR",
              "501 NOT_IMPLEMENTED",
              "502 BAD_GATEWAY",
              "503 SERVICE_UNAVAILABLE",
              "504 GATEWAY_TIMEOUT",
              "505 HTTP_VERSION_NOT_SUPPORTED",
              "506 VARIANT_ALSO_NEGOTIATES",
              "507 INSUFFICIENT_STORAGE",
              "508 LOOP_DETECTED",
              "509 BANDWIDTH_LIMIT_EXCEEDED",
              "510 NOT_EXTENDED",
              "511 NETWORK_AUTHENTICATION_REQUIRED"
            ]
          },
          "timestamp": {
            "type": "string",
            "description": "Дата и время когда произошла ошибка (в формате \"yyyy-MM-dd HH:mm:ss\")",
            "example": "2022-06-09 06:27:23"
          }
        },
        "description": "Сведения об ошибке"
      },
      "UserDto": {
        "required": [
          "email",
          "name"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "Почтовый адрес",
            "example": "petrov.i@practicummail.ru"
          },
          "id": {
            "type": "integer",
            "description": "Идентификатор",
            "format": "int64",
            "readOnly": true,
            "example": 1
          },
          "name": {
            "type": "string",
            "description": "Имя",
            "example": "Петров Иван"
          }
        },
        "description": "Пользователь"
      },
      "CommentDto": {
        "description": "Комментарий (полная информация)",
        "required": [
          "text"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 1
          },
          "text": {
            "type": "string",
            "description": "Текст комментария",
            "example": "Я ждал этого события всю свою жизнь!"
          },
          "author": {
            "$ref": "#/components/schemas/UserDto"
          },
          "event": {
            "$ref": "#/components/schemas/EventCommentDto"
          },
          "createTime": {
            "type": "string",
            "description": "Дата и время создания комментария",
            "example": "2023-10-11 23:10:05"
          },
          "patchTime": {
            "type": "string",
            "description": "Дата и время последнего редактирования комментария",
            "example": "2023-10-15 23:10:05"
          },
          "approved": {
            "type": "boolean",
            "description": "Открыт ли комментарий для просмотра или нет",
            "example": true
          }
        }
      },
      "CommentShortDto": {
        "description": "Комментарий (сокращенная информация)",
        "required": [
          "text"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 1
          },
          "text": {
            "type": "string",
            "description": "Текст комментария",
            "example": "Я ждал этого события всю свою жизнь!"
          },
          "author": {
            "$ref": "#/components/schemas/UserDto"
          },
          "createTime": {
            "type": "string",
            "description": "Дата и время создания комментария",
            "example": "2023-10-11 23:10:05"
          }
        }
      },
      "CommentCreateDto": {
        "description": "Комментарий (DTO для создания нового комментария)",
        "required": [
          "text"
        ],
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "description": "Текст комментария",
            "example": "Хуже этого я ничего не видел"
          }
        }
      },
      "EventCommentDto": {
        "description": "Событие (сокращенная информация для списка комментариев)",
        "required": [
          "title"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 1
          },
          "title": {
            "type": "string",
            "description": "Текст комментария",
            "example": "Пьяные клоуны чинят электрику под песню Я русский"
          }
        }
      }
    }
  }
}